---
author: DTK
date: 2025-01-31
number-offset: 11
format: live-html
---

# 2025-01-31 class notes

```{r include=FALSE}
library(mosaicCalc)
```





$$g(x, y) \equiv a_0 + \underbrace{a_x x + a_y y}_\text{linear terms} \ \ \ + 
\underbrace{a_{xy} x y}_\text{interaction term} +\ \ \  \underbrace{a_{yy} y^2 + a_{xx} x^2}_\text{quadratic terms}$$

What is the order of an interaction term?

To be proficient, a modeler must know how to translate a modeling context into the choice of terms for a low-order polynomial. AVOID terms that you don't need.

[Got to here on Thursday]


## Why do bicycles have gears

Similar to the reason that gasoline cars have gears, but electric cars don't need them.

Bike speed $B$ increases with power applied. You can also think of it as foot speed multiplied by gear ratio.

Muscle Force and speed: There is a decreasing relationship between the force a muscle can apply and the speed of contraction. (Extension is similar, but we need a $\Lambda$-shaped function to put both contraction and extraction into one function.)

Let's keep it simple, use a low-order polynomial, say F(v) = 1 - v. (I'm writing only the sign of the coefficients to make the notation as clean as possible, but in general it should be $F(v) = a - b\ v$).

Power: Power is Force times speed. Work out the dimensions.

Graph the function: multiply the F(v) decreasing function by v, that is

$Power(v) = v (1-v)$

An optimal speed to maximize power!

ASIDE: Gas engines: power proportional to RPM times efficiency of each fuel "event." Efficiency also has an optimal: need to give the gas enough time to burn, but too much leads to "detonation." Ergo, cars have gears.


### Extending the example

Find the speed of a bicycle as a function of road steepness ($s$) and gear ($g$) selected.

- There are of course many other factors that play a crucial role: power ($p$) provided by the cyclist, wind speed, tire inflation, and so on. 

- In our model today, we will consider these other factors fixed. 

### Add in rider power

- Always put in the linear time.

- Are there interactions with other variables?

- Is there an optimum power?

As a first pass, we don't need to consider terms of order three or higher. Examples:

- $p s g$

- $p s^2$ or $p g^2$, let alone $p^2 s^2 g$ (fifth order) and such.

## Operations on Functions

All three of these seek a specific value for the input. That is, these operations 

- take a function as input
- produce a quantity as output

1. Zero-finding

2. Optimization

3. Iteration


After break, we'll start on the famous operations of calculus: differentiation and anti-differentiation. These both take a function as input and produce a function as output.

