---
author: DTK
date: 2025-01-30
number-offset: 10
format: live-html
---

# 2025-01-30 class notes

```{r include=FALSE}
library(mosaicCalc)
```

## Polynomials and their order.

Polynomials are a kind of modeling clay. They can be shaped into several different useful forms.

- Although polynomials were central to your high-school curriculum, there is nothing special about them from a modeling point of view. 
    - Other functions can give the same modeling properties.
    - Even a hand-sketched function can give a good representation of the desired modeling properties. (Later in the course, we'll see how to compute on hand-sketched functions!)
    - DO NOT BE DECEIVED into thinking that they are more precise or meaningful than other similar shapes.
    - We use them from a combination of tradition (ancient), malleability with algebraic tools, and conventions for describing features of function, for example stability of a fixed point or the local shape of a landscape.
    - They are also very simple in terms of calculus properties, both globally and locally. 

- A polynomial is a linear combination of monomials. $x^{-1}$ is NOT a monomial.

- There are other function structures that are important in specific areas, for instance *ratios of polynomials*. We are not going to touch these because they have specialized uses.

- Order of a polynomial is an integer: 1, 2, 3, ...  (but in principle including zero)

- Factoring of polynomials is not a topic of general interest. 

- In calculus textbooks, there is always a section on "Taylor Series," which are polynomials of potentially infinite order. 

    - These are objects of mathematical interest, not of applied interest. The interest is whether and where they converge. The applicability here is that just about *any* function can be approximated by a polynomial and can be made equal as the order goes to infinity. Techniques here are beyond the scope of our course and rarely relevant to applications.
    
- Instead, our focus is on polynomials of finite order. And really, polynomials of low order: two or less.

    - These are incredibly useful in practice.

## Single-input low-order polynomials

You studied univariate low-order polynomials in high school. These are the constant, straight-line, and quadratic (square) functions. 

I want you to think of them as "shapes" rather than formulas. Here are the shapes:

[textbook](https://www.mosaic-web.org/MOSAIC-Calculus/Modeling/12-low-order-polynomials.html#fig-eight-simple-shapes)

Example modeling contexts (from textbook):

1. How many minutes can you run as a function of speed? Concave down and downward sloping: Shape (F). In everyday terms, you wear out faster if you run at high speed.

2. How much fuel is consumed by an aircraft as a function of distance? For long flights, the function is concave up and positive sloping: Shape (D). In everyday terms: fuel use increases with distance, but the amount of fuel you have to carry also increases with distance. A heavy aircraft uses more fuel per mile.

3. How far can you walk as a function of time? Steep-then-shallow and concave down: Shape (E). Your pace slows as you get tired.

4. How does the stew taste as a function of saltiness? There is a local maximum: Shape (H). The taste improves as the amount of salt increases … up to a point. Too much salt and the stew is unpalatable.

5. The incidence of an out-of-control epidemic versus time is concave up, but shallow-then-steep. As the epidemic is brought under control, the decline is steep-then-shallow and concave up. Over the whole course of an epidemic, there is a maximum incidence. Experience shows that epidemics can have a phase where incidence reaches a local minimum: a decline as people practice social distancing followed by an increase as people become complacent.

6. In micro-economic theory there are production functions that describe how much of a good is produced at any given price, and demand functions that describe how much of the good will be purchased as a function of price. As a rule, production increases with price and demand decreases with price.    
    
    In the short term, production functions tend to be concave down, since it is hard to squeeze increased production out of existing facilities. Production functions are Shape (E).
    
    In the short term, some consumers have no other choice than to buy the product, regardless of price. Short-term demand functions are downward sloping, but concave up: Shape C in Figure 12.1. the long term, demand functions can be concave down as consumers find alternatives to the high-priced good. For example, high prices of gasoline may, in the long term, prompt a switch to more efficient cars, hybrids, or electric vehicles. This will push demand for gas guzzlers down steeply.


## Multiple-input low-order polynomials

What's important to us is constructing functions with multiple inputs. We will focus on **two** inputs because it's easiest to develop intuition about them and to display them graphically. But other than graphics, all the concepts apply to low-order polynomials with any number of inputs.


Here is the general formula:

$$g(x, y) \equiv a_0 + a_x x + a_y y + a_{xy} x y + a_{yy} y^2 + a_{xx} x^2$$

We will use a standard set of names to identify the components [here in the textbook](https://www.mosaic-web.org/MOSAIC-Calculus/Modeling/12-low-order-polynomials.html#sec-low-order-two).


$$g(x, y) \equiv a_0 + \underbrace{a_x x + a_y y}_\text{linear terms} \ \ \ + 
\underbrace{a_{xy} x y}_\text{interaction term} +\ \ \  \underbrace{a_{yy} y^2 + a_{xx} x^2}_\text{quadratic terms}$$

What is the order of an interaction term?

To be proficient, a modeler must know how to translate a modeling context into the choice of terms for a low-order polynomial. AVOID terms that you don't need.

[Got to here on Thursday]


## An example

The speed of a bicycle as a function of road steepness ($s$) and gear ($g$) selected.

- There are of course many other factors that play a crucial role: power ($p$) provided by the cyclist, wind speed, tire inflation, and so on. 

- In our model today, we will consider these other factors fixed. 




### Add in rider power

- Always put in the linear time.

- Are there interactions with other variables?

- Is there an optimum power?

As a first pass, we don't need to consider terms of order three or higher. Examples:

- $p s g$

- $p s^2$ or $p g^2$, let alone $p^2 s^2 g$ (fifth order) and such.

## QUIZ






