project:
  type: website
  output-dir: docs

website:
  title: "UATX Calc-I-II, AY 2025"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - resources.qmd

format:
  html:
    theme: litera
    css: styles.css
    toc: true



