project:
  type: website
  output-dir: docs

website:
  title: "MOSAIC Calc 2025"
  navbar:
    left:
      - href: mosaic.qmd
        text: "Mosaic?"
      - href: basics.qmd
        text: Basics
      - href: notes.qmd
        text: Class notes
      - href: assignments.qmd
        text: Assignments
      - href: projects.qmd
        text: Projects

format:
  live-html:
    theme: litera
    css: styles.css
    toc: true

# Enable webR
webr:
  channel-type: 'automatic'
  repos: ["https://dtkaplan.r-universe.dev"]
  packages: ['mosaicCalc', 'ggplot2', 'ggformula']
  #, "LSTbook", "moderndive", "palmerpenguins" ]
filters:
  - webr


