---
title: "UATX/MOSAIC Calculus"
subtitle: "Prof. Daniel Kaplan"
---



------

This is the home page for both terms of the two-term UATX/MOSAIC Calculus sequence. The course has no specific pre-requisites and is suited both to those who have no previous experience with Calculus and those who have taken an AP or IB year-long calculus sequence. The UATX Calculus sequence is designed to replace the entire multi-term traditional sequence---Calc I, II, III, differential equations, linear algebra---for STEM students and is highly relevant to economics, biology and medicine, data science, public policy, physics, and chemistry but does not emphasize "pure" (theoretical) mathematics or proof.

Please read the [**Basics**](basics.html) page for course policies and such. 

------

All of us are busy people and need to regulate how much time we spend on each activity. For UATX calculus, make sure to complete the readings and reading questions. The chapter-by-chapter exercises are also important for learning and as a component of the grade, but you are not obliged (unless otherwise stated) to do *all* the exercises. More is better. Exercises marked as "in-class" are not required homework.

------

[Homework submission link](https://docs.google.com/forms/d/e/1FAIpQLSdvTVopfAxoEUcmXzi7CH6YoTpUzEwy2B3mtLmrgWptfIckVA/viewform?usp=dialog target="_blank")

## Day-by-day schedule


Mid-term break

::: {.callout-note}
## 16. Tuesday 18 February

Topics: Continuous change

Reading: *MOSAIC Calculus* [Chap 17 ](https://www.mosaic-web.org/MOSAIC-Calculus/Textbook/Preliminaries/17-continuous-change.html) and [reading questions](https://dtkaplan.github.io/MC-Workbook/17-reading.html)

Assignment due: [Chapter 16 Exercises](https://dtkaplan.github.io/MC-Workbook/16-exercises.html)
:::



::: {.callout-note}
## 17. Thursday 20 February

Topics: Rate of change

Reading: *MOSAIC Calculus* [Chap 18 ](https://www.mosaic-web.org/MOSAIC-Calculus/Textbook/Differentiation/18-computing.html)
and [reading questions](https://dtkaplan.github.io/MC-Workbook/18-reading.html)

Assignment due: [Chapter 17 Exercises](https://dtkaplan.github.io/MC-Workbook/17-exercises.html)
:::


::: {.callout-note}
## 18. Friday 21 February

Topics: Evanescent $h$

Reading: *MOSAIC Calculus* [Chap 19 ](https://www.mosaic-web.org/MOSAIC-Calculus/Textbook/Differentiation/19-evanescent-h.html) and [reading questions](https://dtkaplan.github.io/MC-Workbook/19-reading.html)

Assignment due: [Chapter 18 Exercises](https://dtkaplan.github.io/MC-Workbook/18-exercises.html)


QUIZ
:::


::: {.callout-note}
## 19. Tuesday 25 February

Topics: Constructing derivatives

Reading: *MOSAIC Calculus* [Chap 20 ](https://www.mosaic-web.org/MOSAIC-Calculus/Textbook/Differentiation/20-computing.html) and [reading questions](https://dtkaplan.github.io/MC-Workbook/20-reading.html)

Assignment due: [Chapter 19 Exercises](https://dtkaplan.github.io/MC-Workbook/19-exercises.html)


:::

::: {.callout-note}
## 20. Thursday 27 February

Topics: Concavity and curvature

Reading: *MOSAIC Calculus* [Chap 21 ](https://www.mosaic-web.org/MOSAIC-Calculus/Textbook/Differentiation/21-concavity.html) and [reading questions](https://dtkaplan.github.io/MC-Workbook/21-reading.html)

Assignment due: [Chapter 20 Exercises](https://dtkaplan.github.io/MC-Workbook/20-exercises.html)

QUIZ

:::

::: {.callout-note}
## 21. Friday 28 February

Topics: Continuity & smoothness

Reading: *MOSAIC Calculus* [Chap 22 ](https://www.mosaic-web.org/MOSAIC-Calculus/Textbook/Differentiation/22-cont-and-smooth.html) and [reading questions](https://dtkaplan.github.io/MC-Workbook/22-reading.html)

Assignment due: [Chapter 20 Exercises](https://dtkaplan.github.io/MC-Workbook/20-exercises.html)
:::


::: {.callout-note}
## 22. Tuesday 4 March

Topics: Derivatives of assembled functions

Reading: *MOSAIC Calculus* [Chap 23 ](https://www.mosaic-web.org/MOSAIC-Calculus/Textbook/Differentiation/23-rules.html) and [reading questions](https://dtkaplan.github.io/MC-Workbook/23-reading.html)

Assignment due: [Chapter 22 Exercises](https://dtkaplan.github.io/MC-Workbook/22-exercises.html)
:::

::: {.callout-note}
## 23 Thursday 6 March

Topics: Optimization

Reading: *MOSAIC Calculus* [Chap 24 ](https://www.mosaic-web.org/MOSAIC-Calculus/Textbook/Differentiation/24-optim.html) and [reading questions](https://dtkaplan.github.io/MC-Workbook/24-reading.html)

Assignment due: [Chapter 23 Exercises](https://dtkaplan.github.io/MC-Workbook/23-exercises.html)

QUIZ
:::

::: {.callout-note}
## 24. Friday 7 March

Topics: Partial differentiation & the gradient vector

Reading: *MOSAIC Calculus* [Chap 25 ](https://www.mosaic-web.org/MOSAIC-Calculus/Textbook/Differentiation/25-partial.html) and [reading questions](https://dtkaplan.github.io/MC-Workbook/25-reading.html)

Assignment due: [Chapter 24 Exercises](https://dtkaplan.github.io/MC-Workbook/24-exercises.html)

:::


::: {.callout-note}
## 25. Tuesday 11 March

Topics: 

Reading: *MOSAIC Calculus* [Chap 26 ](https://www.mosaic-web.org/MOSAIC-Calculus/Textbook/Differentiation/26-approximation.html) and [reading questions](https://dtkaplan.github.io/MC-Workbook/26-reading.html)

Assignment due: [Chapter 25 Exercises](https://dtkaplan.github.io/MC-Workbook/25-exercises.html)

:::

::: {.callout-note}
## 26 Thursday 13 March

Topics: Taylor polynomials

Reading: *MOSAIC Calculus* [Chap 27 ](https://www.mosaic-web.org/MOSAIC-Calculus/Textbook/Differentiation/27-taylor.html) and [reading questions](https://dtkaplan.github.io/MC-Workbook/27-reading.html)

Assignment due: [Chapter 26 Exercises](https://dtkaplan.github.io/MC-Workbook/26-exercises.html)

:::


::: {.callout-note}
## 27. Friday 14 March

Topics: Catch-up & projects with differentiation

Reading: *MOSAIC Calculus* [Differentiation projects ](https://www.mosaic-web.org/MOSAIC-Calculus/Textbook/Differentiation/Differentiation-projects.html) 


Assignment due: [Chapter 27 Exercises](https://dtkaplan.github.io/MC-Workbook/27-exercises.html)

QUIZ on differentiation
:::

::: {.callout-note}
## 28. Tuesday 18 March

Topics: This is the start of a new Block about representing high-dimensional spaces and basic operations on their inhabitants: Vectors and subspaces.

Reading: *MOSAIC Calculus* [Chap 28 ](https://www.mosaic-web.org/MOSAIC-Calculus/Textbook/Linear-combinations/28-Vectors.html) and [reading questions](https://dtkaplan.github.io/MC-Workbook/28-reading.html)

Assignment due: 
:::

::: {.callout-note}
## 29 Thursday 20 March

Topics: Linear combinations of vectors

Reading: *MOSAIC Calculus* [Chap 29 ](https://www.mosaic-web.org/MOSAIC-Calculus/Textbook/Linear-combinations/29-linear-combinations.html) and [reading questions](https://dtkaplan.github.io/MC-Workbook/29-reading.html)

Assignment due: [Chapter 28 Exercises](https://dtkaplan.github.io/MC-Workbook/28-exercises.html)
:::


::: {.callout-note}
## 30. Friday 21 March

Last day of this term!

Review and preview of Spring term component of the course.

QUIZ (30 minutes): Overview of the course.

:::




<!-- THIS IS PAST STUFF. YOU SHOULD BE EDITING ABOVE THIS LINE -->























## Archive



::: {.callout-note}
## 1. Tuesday 7 January, 2025
Topics: Orientation to course resources

Reading:     

- *MOSAIC Calculus* [Preface](https://www.mosaic-web.org/MOSAIC-Calculus/Textbook/)
- *MOSAIC Calculus* [Chap 1: Quantity, function, space](https://www.mosaic-web.org/MOSAIC-Calculus/Textbook/Preliminaries/01-quant-fun-space.html) and [reading questions](https://dtkaplan.github.io/MC-Workbook/01-reading.html). 
:::

::: {.callout-note}
## 2. Thursday 9 January
Topics:

- Clearing up any start-up problems   

- Math and computing notation for *MOSAIC Calculus*

Reading: *MOSAIC Calculus* [Chap 2: Notation](https://www.mosaic-web.org/MOSAIC-Calculus/Textbook/Preliminaries/02-notation.html) and [reading questions](https://dtkaplan.github.io/MC-Workbook/02-reading.html)

Assignments due: 
  - [Chap 1 Exercises](https://dtkaplan.github.io/MC-Workbook/01-exercises.html)


:::

::: {.callout-note}
## 3. Friday 10 January

Topics: Computing for calculus with R

Reading: *MOSAIC Calculus* [Chap 3 Computing with R](https://www.mosaic-web.org/MOSAIC-Calculus/Textbook/Preliminaries/03-computing.html) and [reading questions](https://dtkaplan.github.io/MC-Workbook/03-reading.html)

Assignment due: [Chapter 2 Exercises](https://dtkaplan.github.io/MC-Workbook/02-exercises.html)
:::

::: {.callout-note}
## 4. Tuesday 14 January
Topics: Visualizing functions

Reading: *MOSAIC Calculus* [Chap 4 Visualizing functions](https://www.mosaic-web.org/MOSAIC-Calculus/Textbook/Preliminaries/04-graphs-and-graphics.html) and [reading questions due before class](https://dtkaplan.github.io/MC-Workbook/04-reading.html)

Assignment due: [Chapter 3 Exercises](https://dtkaplan.github.io/MC-Workbook/03-exercises.html)
:::

::: {.callout-note}
## 5. Thursday 16 January
Topics: Our pattern book functions

Reading: *MOSAIC Calculus* [Chap 5 Pattern book functions](https://www.mosaic-web.org/MOSAIC-Calculus/Textbook/Preliminaries/05-pattern-book-functions.html) and [reading questions due before class](https://dtkaplan.github.io/MC-Workbook/05-reading.html)

Assignment due: [Chapter 4 Exercises](https://dtkaplan.github.io/MC-Workbook/04-exercises.html)
:::

::: {.callout-note}
## 6. Friday 17 January

Topics: Describing functions

Reading: *MOSAIC Calculus* [Chap 6 Describing functions ](https://www.mosaic-web.org/MOSAIC-Calculus/Textbook/Preliminaries/06-describing-functions.html) and [reading questions due before class](https://dtkaplan.github.io/MC-Workbook/06-reading.html)

Assignment due: [Chapter 5 Exercises](https://dtkaplan.github.io/MC-Workbook/05-exercises.html)
:::

::: {.callout-note}
## 7. Tuesday 21 January

Topics: Graphics and parameters.

Reading: *MOSAIC Calculus* [Chapter 7]() & [Chapter 8]() and their associated reading questions. Why two chapters in one day? As it happens, Chap. 7 is a rehash of what you have already seen about graphing data from the QR2 course.

Start on exercises for Chaps. 7 & 8. Due Thurs and Fri respectively
:::

::: {.callout-note}
## 8. Thursday 23 January

Topics: Assembling functions

Reading: *MOSAIC Calculus* [Chapter 9](https://www.mosaic-web.org/MOSAIC-Calculus/Textbook/Modeling/09-assembling-functions.html) & its associated reading questions. 

Assignment Due: [Chapter 7 exercises](https://dtkaplan.github.io/MC-Workbook/07-exercises.html)
:::


::: {.callout-note}
## 9. Friday 24 January

Topics: Fitting function features

*Note*: We are covering Ch **11** and deferring Chapter 10 until next Tuesday.

Reading: *MOSAIC Calculus* [Chapter 11](https://www.mosaic-web.org/MOSAIC-Calculus/Textbook/Modeling/11-fitting-features.html) & its associated reading questions. 

Assignment Due: [Chapter 8 exercises](https://dtkaplan.github.io/MC-Workbook/08-exercises.html)

Start on: 

- [Chapter 11 exercises](https://dtkaplan.github.io/MC-Workbook/11-exercises.html) (but not the project)

:::

::: {.callout-note}
## 10. Tuesday 28 January

Topics: Fitting function features

*Note*: Chapter 10 today!

Reading: *MOSAIC Calculus* [Chapter 10](https://www.mosaic-web.org/MOSAIC-Calculus/Textbook/Modeling/10-functions-with-multiple-inputs.html) & its associated reading questions. 

Assignment Due: [Chapter 11 exercises](https://dtkaplan.github.io/MC-Workbook/11-exercises.html) (but not the project)

Start on:

- [Chapter 9 exercises](https://dtkaplan.github.io/MC-Workbook/09-exercises.html) numbers 1 through 8
- [Chapter 10 exercises](https://dtkaplan.github.io/MC-Workbook/10-exercises.html) (but not the "class activity")
:::


::: {.callout-note}
## 11. Thursday 30 January

Reading: *MOSAIC Calculus* [Chapter 12](https://www.mosaic-web.org/MOSAIC-Calculus/Textbook/Modeling/12-low-order-polynomials.html) and [reading questions](https://dtkaplan.github.io/MC-Workbook/12-reading.html)

QUIZ through Chapter 10

Assignmenta Due: 

- [Chapter 9 exercises](https://dtkaplan.github.io/MC-Workbook/09-exercises.html) numbers 1 through 8
- [Chapter 10 exercises](https://dtkaplan.github.io/MC-Workbook/10-exercises.html) (but not the "class activity")

Start on: Assignment Due: [Chapter 12 exercises](https://dtkaplan.github.io/MC-Workbook/12-exercises.html) (but not the project)


:::


::: {.callout-note}
## 12. Friday 31 January

Reading: *MOSAIC Calculus* [Chapter 13](https://www.mosaic-web.org/MOSAIC-Calculus/Textbook/Modeling/13-operations.html) and [reading questions](https://dtkaplan.github.io/MC-Workbook/13-reading.html)

Assignment Due: 

- [Chapter 12 exercises](https://dtkaplan.github.io/MC-Workbook/12-exercises.html) 

Start on: [Chapter 13 exercises](https://dtkaplan.github.io/MC-Workbook/13-exercises.html) 

:::

::: {.callout-note}
## 13. Tuesday 4 February

Reading: *MOSAIC Calculus* [Chapter 14](https://www.mosaic-web.org/MOSAIC-Calculus/Textbook/Modeling/14-magnitudes.html) and [reading questions](https://dtkaplan.github.io/MC-Workbook/14-reading.html)

Assignment Due: [Chapter 13 exercises](https://dtkaplan.github.io/MC-Workbook/13-exercises.html) 

Start on: [Chapter 14 exercises](https://dtkaplan.github.io/MC-Workbook/14-exercises.html) 



:::


::: {.callout-note}
## 14. Thursday 6 February

Reading: *MOSAIC Calculus* [Chapter 15](https://www.mosaic-web.org/MOSAIC-Calculus/Textbook/Modeling/15-dimensions.html) and [reading questions](https://dtkaplan.github.io/MC-Workbook/15-reading.html)

Assignment Due: [Chapter 14 exercises](https://dtkaplan.github.io/MC-Workbook/15-exercises.html) 

Start on: 

- [Chapter 9 exercises](https://dtkaplan.github.io/MC-Workbook/12-exercises.html) number 9 through 18 (due by end of reading week)
- [Chapter 15 exercises](https://dtkaplan.github.io/MC-Workbook/15-exercises.html) (due by end of reading week)


:::

::: {.callout-note}
## 15. Friday 7 February

Reading: **MOSAIC Calculus* [Chapter 16](https://www.mosaic-web.org/MOSAIC-Calculus/Textbook/Modeling/16-modeling-scientific-method.html) and [reading questions](https://dtkaplan.github.io/MC-Workbook/16-reading.html)

Assignment due: (by end of reading week)

- [Chapter 9 exercises](https://dtkaplan.github.io/MC-Workbook/12-exercises.html) number 9 through 18 
- [Chapter 15 exercises](https://dtkaplan.github.io/MC-Workbook/15-exercises.html) 

QUIZ through Chapter 15

:::



