---
title: UATX, Innovation, STEM & MOSAIC
---

University of Austin is founded on several principles. Among these is a conviction that many of the problems in higher education can best be solved by starting a new institution that is free to innovate creatively and productively. 

An important locus for innovation is STEM education, especially traditional structures that do not correspond to the needs of a technically educated person in today's world. The problems begin with calculus. Emerging from the Enlightenment world of the 1700s, calculus powered developments in science that form the basis of much of contempory life, for instance the technology of engines, electricity, and communication. The first calculus textbook was published in 1696. Its contents are recognizably present in today's Calc I course despite the advent of technologies that were unimagined when the book was written. Even the simple pencil is more modern, but the epoch-changing technology is the computer. Among all the other things, computers enable a restructuring of the concepts of calculus that make them more accessible and applicable to real-world problems.

Universities are famously allergic to change in existing curricula. Calculus, as it became more applicable to more settings and topics, grew by accretion over two and a half centuries: adding a second course, then a third, and then for STEM students a fourth and fifth. The content of these courses was set by theoretical mathematicians who, understandably, focus on their own professional interests and the aesthetic of their discipline. 

It's illuminating to think of these courses in terms of dishes a meal. But unlike a real meal, the order content of the dishes is not coordinated and regulated to make a palatable and digestible whole. It's just one plate of food after the other. The result would be predicable to a diner: most people are full after the first plate and leave the table. A few, with hearty digestions, can stomach the second and sometimes the third plate, but there is no room left for dessert. 

To create a sensible meal for STEM students, we need to reduce the number of dishes and pay attention to what we know today about nutritional content. For instance, the five-plate traditional meal has no room for data and statistics, machine learning and other modern mathematical technologies, or even computing.

Based on preliminary curricular work in the 1990s, Project MOSAIC was funded in 2009 by the US National Science Foundation to design a modern meal suited to modern needs and appetites. Important additional work was sponsored by the US Air Force Academy. The MOSAIC is constructed by shattering the traditional plates, picking the important pieces out and re-arranging them and grouting them together with modern concepts and technologies to produce a coherent picture.

At UATX, MOSAIC Calculus is a two-term course that comprises a complete mathematical program for STEM students. Elements come from all five semesters of the traditional sequence, but have been carefully selected and amended with a pedagogy designed to avoid the algebraic pitfalls that, in the convention scheme, prevent most students even from reaching calculus, let alone progressing to a second or third course.

Students arrive at UAustin with varied mathematical preparations and talents. Some students have already studied calculus, many have not. The MOSAIC curriculum has been designed to be accessible and worthwhile for all students. Even a student with one or two semesters of high-school calculus should enroll for the first semester of MOSAIC Calculus. Based on extensive experience over a couple of decades, students will find little that is repetitive with their earlier studies. After all, we're a long way past the Calc I curriculum founded in 1696.

For the reader familiar with university-level mathematical topics .... MOSAIC Calculus is multi-variable from the start, organized around building models of real-world systems, engages linear algebra (which is the foundation of modern scientific mathematical work), dynamical systems, dimensions of physical quantities, and modern modes of constructing functions from data. It is not a machine-learning course, but it does cover the foundations of this. It also provides a solid introduction to technical computing, which is used both to develop conceptual understanding and to build and manipulate mathematical models. 
