---
title: Week 20 In-Class Assessment
date: 2025-06-12
categories: []
format:
  typst:
    papersize: us-letter
    margin:
      left: 1cm
      right: 8cm
      top: 1cm
      bottom: 1cm
    columns: 1
    shift-heading-level-by: -1
    
crossref:
  chapters: true
  exr-title: "Question"
  exr-prefix: "Question"
---

```{r include=FALSE}
library(mosaicCalc)
library(LSTbook)
library(devoirs)
source("../../_software/software.r")
source("_software/for_20.R")
devoirs::answer_style("none") 
# devoirs::answer_style("block") 
```


MAKE IT NOT WORK

```{r}
stop("Stopping assignment 20")
```


{{< include _exercises/daisy-lick-rug2.qmd >}}

-------------

{{< include _exercises/avoid-ring-cotton2.qmd >}}

-------------

{{< include _exercises/niece-dream-boat2.qmd >}}

------------

{{< include _exercises/ape-know-futon2.qmd >}}

------------

{{< include _exercises/fir-bathe-jacket.qmd >}}

------------

{{< include _exercises/rhinosaurus-throw-gloves2.qmd >}}

------------

{{< include _exercises/doe-swim-door2.qmd >}}

