---
author: DTK
date: 2025-04-24
number-offset: 40
format: live-html
webr:
  channel-type: 'automatic'
  repos: ["https://dtkaplan.r-universe.dev"]
  packages: ['ggplot2', 'mosaicCalc', "LSTbook" ]
filters:
  - webr
---

{{< include ../../_extensions/r-wasm/live/_knitr.qmd >}}

```{r include=FALSE}
library(mosaicCalc)
library(LSTdata)
source("../../_software/software.R")
```
::: {.callout-tip collapse=true}
## Background software
```{webr-r}
#| autorun: true
#| context: output
{{< include ../../_software/software.R >}}
```
:::


Survival to age n

In class:
```{r}
Two <- SSA2021F |>
  mutate(survive = 1 - mortality) |>
  mutate(total_survival =  cumprod(survive))
```




# 2025-04-24 class notes

Mortality table from Social Security Administration

```{r}
head(SSA2021F)
```


Create mortality as a continuous function of age:

```{r}
mortality <- mosaic::spliner(mortality ~ age, data = SSA2021F)
Lsurvival <- makeFun(log(1 - mortality(age)) ~ age)
Accumulated <- antiD(Lsurvival(age) ~ age)
slice_plot(exp(Accumulated(age)) ~ age, domain(age = 0:120))
```









```{webr-r}
#| caption: User console A
#| persist: true
```

```{webr-r}
#| caption: User console B
#| persist: true
```

```{webr-r}
#| caption: User console C
#| persist: true
```


