---
id: "dog-chew-candy"
created: "Mon Apr 14 11:45:02 2025"
attribution: TBA
---


::: {#exr-dog-chew-candy}
## R^2^ and residuals
We'll use `mtcars` to demonstrate finding R^2^ using the `qr.solve()` mechanics.



Part a
: Build a model matrix and target vector from `mtcars` corresponding to the model specification `disp ~ cyl + hp`. (Hint: Don't forget the intercept term!)


<!-- Start of rich webr chunk dcc-3ul -->

::: {.panel-tabset page-layout=custom}
## Webr chunk
```{webr-r}
#| caption: For part a
#| persist: true
#| label: dcc-3ul-main


```

## Code submission
`r devoirs_text("dcc-3ul", "For part a.")`


## Scratch 1
```{webr-r}
#| caption: Scratch work panel 1
#| persist: true
#| label: dcc-3ul-scratch1
```

## Scratch 2
```{webr-r}
#| caption: Scratch work panel 2
#| persist: true
#| label: dcc-3ul-scratch1
```
:::
<!-- end of enriched webr chunk dcc-3ul -->

<!-- Opening answer: ia1-2LZ -->
::: {.callout-tip collapse=true `r answer_style()`}
## Answer{data-tooltip="Ans id: ia1-2LZ"}

```{webr-r}
M <- with(mtcars, cbind(vec(cyl), vec(hp), 1))
b <- with(mtcars, vec(disp))
```

[..id..]{data-tooltip="Ans id: ia1-2LZ"}
:::
<!-- closing answer ia1-2LZ -->

Part b
: Compute the fitted model values vector from the model in Part a. Call this `bhat` for future reference.

<!-- Opening answer: ia1-4Iw -->
::: {.callout-tip collapse=true `r answer_style()`}
## Answer{data-tooltip="Ans id: ia1-4Iw"}

```{webr-r}
x <- qr.solve(M, b)
bhat <- M %*% x
```


[..id..]{data-tooltip="Ans id: ia1-4Iw"}
:::
<!-- closing answer ia1-4Iw -->
Part c
: Compute the residual vector from the model in Part a. Call this `resid` for future reference.



<!-- Start of rich webr chunk dcc-2QV -->

::: {.panel-tabset page-layout=custom}
## Webr chunk
```{webr-r}
#| caption: For part c
#| persist: true
#| label: dcc-2QV-main


```

## Code submission
`r devoirs_text("dcc-2QV", str="For part c.")`


## Scratch 1
If you need to, do computations on the side to check things out!
```{webr-r}
#| caption: Scratch work panel 1
#| persist: true
#| label: dcc-2QV-scratch1
```

## Scratch 2
More on-the-side computations if you need.
```{webr-r}
#| caption: Scratch work panel 2
#| persist: true
#| label: dcc-2QV-scratch1
```
:::
<!-- end of enriched webr chunk dcc-2QV -->
`r devoirs_text("Enter your residual vector here.")`

<!-- Opening answer: ia1-8Qx -->
::: {.callout-tip collapse=true `r answer_style()`}
## Answer{data-tooltip="Ans id: ia1-8Qx"}

```{webr-r}
resid <- b - bhat
```


[..id..]{data-tooltip="Ans id: ia1-8Qx"}
:::
<!-- closing answer ia1-8Qx -->

Part d
: Using `bhat` and the target vector, compute the R^2^ as a ratio of variances. Compare this to the answer you get when you use the `model_train() |> R2()` mechanics.

<!-- Opening answer: ia1-6lx -->
::: {.callout-tip collapse=true `r answer_style()`}
## Answer{data-tooltip="Ans id: ia1-6lx"}

```{webr-r}
var(bhat) / var(b)
```

[..id..]{data-tooltip="Ans id: ia1-6lx"}
:::
<!-- closing answer ia1-6lx -->

Part e
: Demonatrate that `bhat` plus `resid` equals the target vector.

<!-- Opening answer: ia1-7vy -->
::: {.callout-tip collapse=true `r answer_style()`}
## Answer{data-tooltip="Ans id: ia1-7vy"}

Best to do this by constructing the sum, subtracting `b`, then looking at the length of the result.
```{webr-r}
veclen( bhat + resid - b)
```

[..id..]{data-tooltip="Ans id: ia1-7vy"}
:::
<!-- closing answer ia1-7vy -->


<!-- Start of rich webr chunk dcc-7vI -->

::: {.panel-tabset page-layout=custom}
## Webr chunk
```{webr-r}
#| caption: For parts c and d
#| persist: true
#| label: dcc-7vI-main


```

## Code submission
`r devoirs_text("dcc-7vI", str="Code and results from parts (c) and (d)")`


## Scratch 1
```{webr-r}
#| caption: Scratch work panel 1
#| persist: true
#| label: dcc-7vI-scratch1
```

## Scratch 2
```{webr-r}
#| caption: Scratch work panel 2
#| persist: true
#| label: dcc-7vI-scratch1
```
:::
<!-- end of enriched webr chunk dcc-7vI -->
:::


