---
author: DTK
date: 2025-04-04
number-offset: 32
format: live-html
---



```{r include=FALSE}
library(mosaicCalc)
library(purrr)
library(LSTbook)
{{< include ../../_software/software.R >}}
```



# 2025-04-04 class notes

::: {.callout-tip collapse=true}
## Console A
```{webr-r}
#| persist: true

```
:::

::: {.callout-tip collapse=true}
## Console B
```{webr-r}
#| persist: true

```
:::

::: {.callout-tip collapse=true}
## Console C
```{webr-r}
#| persist: true

```
:::

## Dot product and the correlation coefficient

Here's the way we did things in QR2:

```{webr-r}
Galton |> model_train(height ~ mother) |>
  R2()
```

The correlation coefficient is the square root of R^2^ for for a model with only one explanatory variable where both the response and the explanatory variables are quantitative.

```{webr-r}
sqrt(0.0406647)
```

Now let's compute the dot-product and the cosine of the inclusive angle by data wrangling. 

```{webr-r}
Galton |>
  mutate(standardH = (height - mean(height))/sd(height),
         standardM = (mother - mean(mother))/sd(mother)) |>
  summarize(dotproduct = sum(standardH * standardM),
            lenH = sqrt(sum(standardH^2)),
            lenM = sqrt(sum(standardM^2)),
            cosTheta = dotproduct / (lenH * lenM))
```
## Addition

## Scaling

Scaling provides the way to turn a vector into a space.

## Linear combination

A way to produce a space defined by two or more vectors.

What is modeling in terms of vectors. Find the best linear combination of vectors (explanatory terms) to approximate the response vector.



## Functions as vectors

Gaussians over a two second-window

```{webr-r}
step = 2^(1/12)

Sounds <- tibble::tibble(
  time = (0:44100)/22050,
  g1 = pmin(1.0, dnorm(time, mean = 1, sd=0.5)),
  g2 = pmin(1.0, dnorm(time, mean = 0.25, sd=0.2)),
  g3 = pmin(1.0, dnorm(time, mean = .75, sd=0.2)),
  g4 = pmin(1.0, dnorm(time, mean = 1.25, sd=0.1)),
  one =    sin(step^0  * 2 * pi * 440 * time),
  two =    sin(step^1  * 2 * pi * 440 * time),
  three =  sin(step^2  * 2 * pi * 440 * time),
  four =   sin(step^3  * 2 * pi * 440 * time),
  five =   sin(step^4  * 2 * pi * 440 * time),
  six =    sin(step^5  * 2 * pi * 440 * time),
  seven =  sin(step^6  * 2 * pi * 440 * time),
  eight =  sin(step^7  * 2 * pi * 440 * time),
  nine =   sin(step^8  * 2 * pi * 440 * time),
  ten =    sin(step^9  * 2 * pi * 440 * time),
  eleven = sin(step^10 * 2 * pi * 440 * time),
  twelve = sin(step^11 * 2 * pi * 440 * time)
)  |>
  mutate(sum = g2*three + g2*five + g2*seven + 2*three^2)

# audio::play(Sounds$sum / 10, rate = 22050)
```

## Matrices

Matrix of random numbers

```{webr-r}
Mrand <- matrix(rnorm(40*30), nrow=40, ncol=30)
draw_matrix(Mrand)
```

## Subspaces

What's the subspace spanned by 3 vectors on a table?

## SVD and the dimension of subspaces

Create some vectors, then some linear combinations of them than look at the singular values.

```{webr-r}
u <- rbind(1,2,3, 6, -2)
v <- rbind(2,5,3, -4, 1)
w <- 3*u - 2*v
x <- w - u
y <- u + v - w
M <- cbind(u, v, w, x, y)
M |> svd() |> purrr::pluck("d")
```

```{webr-r}
draw_matrix(M)
M
```

```{webr-r}
M <- Sounds |> 
  select(one, two, three, four, five, 
         six, seven, eight, nine, ten, eleven, twelve) |>
  as.matrix(ncol = 12) 
M |> svd() |> purrr::pluck("d")
```

```{webr-r}
#| results: hide
#| autorun: true
{{< include ../../_software/software.R >}}
```
