---
id: "birch-ring-pen"
created: "Mon Jun  2 16:11:54 2025"
attribution: TBA
---

```{r include=FALSE, eval=!"devoirs" %in% (.packages())}
# For stand-alone compilation testing
library(devoirs)
library(mosaicCalc)
```

::: {#exr-birch-ring-pen}
We're going to make some "random" dynamics. That is, we'll construct the dynamical system

$$\partial_t x = f(x, y)\\ \ \ \ \ \ 
\partial_t y = g(x,y)$$

where $f()$ and $g()$ are random functions.

@fig-f-g-202-a shows the nullclines for the flow and shows short trajectories from about 60
randomly selected initial conditions.

::: {#fig-f-g-202-a}

```{r}
#| echo: false
#| warning: false
f <- doodle_fun(~ x & y, seed = 202)
g <- doodle_fun(~ x & y, seed = 678)
dom = domain(x = -7:2.5, y = -2.5:7)
streamlines(dx ~ f(x,y), dy ~ g(x,y), dom, dt = 0.025) |>
contour_plot(f(x,y) ~ x & y, dom, contours_at =  0, contour_color = "blue") |>
  contour_plot(g(x,y) ~ x & y, dom, contours_at =  0, contour_color = "tomato") |>
  gf_theme(theme_minimal())
  
```

:::

Part 1
: Which is the $x$-nullcline?
```{mcq}
#| label: f-g-202-1
#| inline: true
1. Red [hint: When the trajectories cross the red nullcline, they are going horizontally. So red can't be the $x$ nullcline.]
2. Blue [correct]
```

Part 2
: How many fixed points are in the domain shown in the graph?
```{mcq}
#| label: f-g-202-2
#| inline: true
1. 0
2. 1
3. 2 [correct hint: Any point where an x-nullcline crosses a y-nullcline is a fixed point.]
4. 3
5. 4
6. Not enough information
```

Part 3
: Which of these characterizes the eigenvalues of the linear flow near the rightmost fixed point?
```{mcq}
#| label: f-g-202-3
1. Both real; both positive
2. Both real; both negative
3. Both real; one positive and one negative.
4. Both complex; stable [correct]
5. Both complex: unstable [hint: But admittedly it's hard to tell is the trajectories are circling toward or away from the fixed point.]
6. One complex, one real [hint: Impossible! If one is complex, the other must be its complex conjugate.]
```

Part 4
: Which of these characterizes the eigenvalues of the linear flow near the leftmost fixed point?
```{mcq}
#| label: f-g-202-4
1. Both real; both positive
2. Both real; both negative
3. Both real; one positive and one negative. [correct hint: in other words, a saddle]
4. Both complex; stable [hint: The trajectories on either side of the x-nullcline are pointing away from each other, not circling.]
5. Both complex: unstable [hint: The trajectories on either side of the y-nullcline are pointing toward one another]
6. One complex, one real [hint: Impossible! If one is complex, the other must be its complex conjugate.]
```


:::
 <!-- end of exr-birch-ring-pen -->
