---
author: DTK
date: 2025-06-06
number-offset: 41
format: live-html
webr:
  channel-type: 'automatic'
  repos: ["https://dtkaplan.r-universe.dev"]
  packages: ['ggplot2', 'mosaicCalc', "LSTbook" ]
filters:
  - webr
---

{{< include ../../_extensions/r-wasm/live/_knitr.qmd >}}

```{r include=FALSE}
library(mosaicCalc)
library(devoirs)
source("../../_software/software.R")
```
::: {.callout-tip collapse=true}
## Background software
```{webr-r}
#| autorun: true
#| context: output
{{< include ../../_software/software.R >}}
```
:::

```{r}
theta <- 2*pi - .01 #pick a random number
strange <- exp(theta * 1i)

strange

```

```{r}
strange * Conj(strange)
Arg(strange)*180/pi
theta*180/pi 
```

```{r}
M <- matrix(rnorm(64), nrow=8)
round(M, 2)
eigen(M)
```















* Return to life expectancy
* How do changes in mortality compare to changes in birth rate.
* Fertility vs age
* Propagating the population age distribution

# 2025-06-06 class notes

```{webr-r}
#| caption: User console A
#| persist: true
```

```{webr-r}
#| caption: User console B
#| persist: true
```

```{webr-r}
#| caption: User console C
#| persist: true
```


