---
title: MOSAIC Week 12 Assignment
date: 2025-04-03
format: live-html
categories: [linear algebra]
---

```{r include=FALSE}
library(mosaicCalc)
library(LSTbook)
library(devoirs)
source("../../_software/software.R")
# for composing questions ...
matrix2latex <- function(matr) {

printmrow <- function(x) {

    cat(cat(x,sep=" & "),"\\\\ \n")
}

cat("\\left(\\begin{array}{r}","\n")
body <- apply(matr,1,printmrow)
cat("\\end{array}\\right)")
}
Lmat <- function(nr, nc) {
  values_mat(nr, nc) |> matrix2latex()
}
```

{{< include ../../_software/devoirs.qmd >}}

<!-- ::: {.callout-warning collapse=true}
## Background software -->
```{webr-r}
#| autorun: true
#| context: output
#| echo: false
#| caption: Background software
#| 
{{< include ../../_software/software.R >}}
```
<!-- ::: -->

## By hand and eye

::: {.panel-tabset}

## Exer 1 
{{< include _exercises/matrix-0.qmd >}}

## Exer 2 
{{< include _exercises/matrix-1.qmd >}}

## Exer 3
{{< include _exercises/matrix-2.qmd >}}

## Exer 4 
{{< include _exercises/matrix-3.qmd >}}

## Exer 5
{{< include _exercises/matrix-4.qmd >}}

## Exer 6
{{< include _exercises/matrix-5.qmd >}}

## Exer 7
{{< include _exercises/matrix-6.qmd >}}

## Exer 8
{{< include _exercises/matrix-7.qmd >}}

## Exer 9
{{< include _exercises/matrix-8.qmd >}}

## Exer 10
{{< include _exercises/elephant-hit-pot.qmd >}}
:::


## Computing

::: {.callout-tip collapse="true"}
## Note on submitting code and responses

The `{devoirs}` package has changed. In the old version, your R-chunks were collected automatically when you press the "collect answers" button. That is no longer true.

Instead, there will be a set of "tabs" collected together. You can do your calculations in any of the Webr or "scratch" chunks---they all talk to one another. Put your response to the question in the "Submission" text box.

Both your code and your "submission" will be preserved in your browser. CAUTION: When you return to the document, the code chunks will be filled in with your last entry, but you will have to run the chunk (if needed) by pressing the "Run Code" button. 


<!-- Start of rich webr chunk ia1-7Wi -->

Example: What is 12 + 3?

::: {.panel-tabset page-layout=custom}
## Webr chunk
```{webr-r}
#| caption: Webr chunk
#| persist: true
#| label: ia1-7Wi-main


```

## Submission
`r devoirs_text("ia1-7Wi")`


## Scratch 1

```{webr-r}
#| caption: Scratch work panel 1
#| persist: true
#| label: ia1-7Wi-scratch1
```

## Scratch 2

```{webr-r}
#| caption: Scratch work panel 2
#| persist: true
#| label: ia1-7Wi-scratch1
```
:::
<!-- end of enriched webr chunk ia1-7Wi -->
:::

::: {.panel-tabset}
## Exer 12.11
{{< include _exercises/make-ortho-1.qmd >}}

## Exer 12.12
{{< include _exercises/rotation-matrix-by-hand.qmd >}}

## Exer 12.13
{{< include _exercises/resid-from-u.qmd >}}

## Exer 12.13
{{< include _exercises/cat-cost-radio.qmd >}}

## Exer 12.15
{{< include _exercises/frog-close-chair.qmd >}}
:::

