---
title: MOSAIC Week 16 Assignment
date: 2025-05-09
categories: [linear algebra]
---
```{r include=FALSE}
library(mosaicCalc)
library(LSTbook)
library(devoirs)
source("../../_software/software.r")
devoirs::answer_style("none") 
# devoirs::answer_style("block") 
```

{{< include ../../_software/devoirs.qmd >}}

```{webr-r}
#| autorun: true
#| context: output
#| echo: false
#| results: hide
{{< include ../../_software/software.R >}}
```

## Chapter 37

## Chapter 38 



{{< include ../../../../MC-Workbook/Block_4/walnut-bet-pants.qmd >}}

{{< include ../../../../MC-Workbook/Block_4/pony-stand-bottle.qmd >}}

::: {.callout-note collapse=true}
## Chapter 48

{{{< include _Chap48.qmd >}}}

:::


::: {.callout-note collapse=true}
## Chapter 35
{{< include _Chap35.qmd >}}
:::



## Splines

Find the shape of the solar power curve for a given week in the year. Do this 
for several weeks during the year. Combination of wrangling to pull out the weeks (across all years) then finding the max at each timestamp, then splining through this to find the cloudiness.

DRAFT

for a possible solar power problem 
For instance, if I had a function ('solarpanelpower') that calculates the amount of power a solar panel generates and another function ('sunlight') that tells me the amount of sunlight at time of the day ('TOD'). I could evaluate this in one step like the following: 'solarpanelpower(sunlight(TOD))'. This would give me the amount of power from the solar panel based upon the time of the day.
:::


::: {.panel-tabset}
## Exer 16.1


## Exer 16.2


::: 
<!-- end of hand-and-eye tabset -->

## Computing

::: {.panel-tabset}
## 16.C.3


## 16.C.4


## 16.C.5


## 16.C.6

:::
<!-- end of computing tabset -->

